# Generated by Django 5.0.1 on 2025-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('greet', 'Greet'), ('wave', 'Wave'), ('dance', 'Dance'), ('idle', 'Idle'), ('custom', 'Custom')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Avatar Action',
                'verbose_name_plural': 'Avatar Actions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScanCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scan Count',
                'verbose_name_plural': 'Scan Counts',
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
