# Generated by Django 5.0.1 on 2025-09-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=255, unique=True)),
                ('first_scan', models.DateTimeField(auto_now_add=True)),
                ('last_scan', models.DateTimeField(auto_now=True)),
                ('total_scans', models.IntegerField(default=1)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_info', models.JSONField(blank=True, null=True)),
                ('hardware_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_scan'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Count',
                'verbose_name_plural': 'Device Counts',
            },
        ),
    ]
